name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - run: echo "Checkout completado"

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      
      - run: echo "JDK configurado"

